# 请求参数不存在
PARAMETER_MISSING_ERROR = "PARAMETER_MISSING_ERROR"
# 参数错误
PARAMETER_VALUE_ERROR = "PARAMETER_VALUE_ERROR"
#  改方法不支持GET
GET_DENIED_FOR_THIS_METHOD = "GET_DENIED_FOR_THIS_METHOD"
# 登陆失败
LOGIN_ERROR = "LOGIN_ERROR"
# 用户未登陆
NOT_LOGIN = "NOT_LOGIN"
# JAVA服务连接错误，可能是由于JAVA服务没有开启，请联系管理员
PY4J_CONNECTION_ERROR = "PY4J_CONNECTION_ERROR"
# 集群网络不通或查询错误
DB_QUERY_ERROR = "db000"
# 数据库连接失败
DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
# 已存在重名数据，请修改数据名称
DATA_NAME_HAS_BEEN_USED = "DATA_NAME_HAS_BEEN_USED"
# 超过最大上传大小
MY_DATA_UPLOAD_SIZE_EXCEED = "MY_DATA_UPLOAD_SIZE_EXCEED"
